services:
    
    ################################################################################
    # SPLASH Optilog Connector Service
    splash.connectors.recommerce:
        class:      Splash\Connectors\ReCommerce\Services\ReCommerceConnector
        autowire:   true
        tags:
            - { name: "splash.connector" }
            
    ################################################################################
    # Enables Dependency Injection in Controller Actions
    Splash\Connectors\ReCommerce\Controller\:
        resource:   '../../Controller'
        public:     true
        tags:
            - { name: 'controller.service_arguments' }