services:
    _defaults:
        autowire:       true
        autoconfigure:  true
    
    ################################################################################
    # SPLASH Optilog Connector Service
    splash.connectors.recommerce:
        class:      Splash\Connectors\ReCommerce\Services\ReCommerceConnector
        calls:
            - setMetaDir: ["%kernel.cache_dir%"]
        tags:
            - { name: "splash.connector" }
            
    ################################################################################
    # Enables Dependency Injection in Actions
    Splash\Connectors\ReCommerce\Actions\:
        resource:   '../../Actions'
        tags:
            - { name: 'controller.service_arguments' }