
splash:

################################################################################    
# Configure Splash Bundle Parameters Cache    
# Cache is Enabled by Default to Store Custom Connectors Configuration
# If disabled, configuration must be store in Static, on connections section
################################################################################    
#    cache: 
#        enabled: false    
#        lifetime: 10

    # Allow Notifications for Generic Users   
    notify: ["ROLE_USER"]
    
################################################################################    
# List of Available Connector Connections
################################################################################    

    connections:
        
        ########################################################################
        # Recommerce SandBox
        ReCommerce-SandBox:
            id:                 ThisIsSandBoxWsId
            key:                ThisIsNotASecretKeyForSandBox
            name:               ReCommerce Sandbox
            connector:          recommerce
            ########################################################################
            # FAKE CREDENTIALS : ASK YOURS TO YOUR MAIN RECOMMERCE CONTACT
            ########################################################################
            config:
                WsHost:         http://sandbox.recommerce.local
                ApiKey:         ThisIsSecretApiKey
                isSandbox:      true

        ########################################################################
        # Recommerce Staging
#        ReCommerce-Staging:
#            id:                 ThisIsStagingWsId
#            key:                ThisIsNotASecretKeyForStaging
#            name:               ReCommerce Staging
#            connector:          recommerce
#            ########################################################################
#            # FAKE CREDENTIALS : ASK YOURS TO YOUR MAIN RECOMMERCE CONTACT
#            ########################################################################
#            config:
#                WsHost:         https://stage-processing-shipment-api.stage-api.recommerce.cloud
#                ApiKey:         a0e2cfefdb9946be8402673fc7ceaad5